version: '3.1'

services:
  elasticsearch_container:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - ELASTIC_PASSWORD=1234
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9199:9200"
      - "9299:9300"

  kibana_container:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana_container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_container:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=1234
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch_container
